logging:
  level: debug
spring:
  application:
    name: SpringJPARedis

  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/springdata?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: JpaDataHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      ddl-auto: create-drop
  cache:
    type: redis
  #单机版
  redis:
    host: localhost #matser的ip地址
    port: 6379 #端口号
    password: 123456 #如果有密码
    database: 15 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    timeout: 300000 # 连接超时时间（毫秒）
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-idle: 10 # 连接池中的最大空闲连接 默认 8
      min-idle: 2 # 连接池中的最小空闲连接 默认 0
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
    #哨兵模式
#    timeout: 300000 # 连接超时时间（毫秒）
#    pool:
#      max-active: -1 # 连接池最大连接数（使用负值表示没有限制） 默认 8
#      max-idle: 10 # 连接池中的最大空闲连接 默认 8
#      min-idle: 2 # 连接池中的最小空闲连接 默认 0
#      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#    sentinel:
#      master: mymaster #哨兵监听redis server名称
#      nodes: 192.168.12.194:26379,192.168.12.194:36379,192.168.12.194:46379 #哨兵配置列表
    #集群模式
#    timeout: 300000 # 连接超时时间（毫秒）
#    pool:
#      max-active: -1 # 连接池最大连接数（使用负值表示没有限制） 默认 8
#      max-idle: 10 # 连接池中的最大空闲连接 默认 8
#      min-idle: 2 # 连接池中的最小空闲连接 默认 0
#      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#    cluster:
#      max-redirects: 3
#      nodes:
#        - 192.168.100.131:6001
#        - 192.168.100.132:6002
#        - 192.168.100.133:6003
#        - 192.168.100.134:6004
#        - 192.168.100.135:6005
#        - 192.168.100.136:6006

server:
  port: 8088