logging:
  level: debug
spring:
  application:
    name: SpringJPARedis

  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/springdata?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: JpaDataHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      ddl-auto: create-drop
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 15 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    timeout: 300000 # 连接超时时间（毫秒）
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-idle: 10 # 连接池中的最大空闲连接 默认 8
      min-idle: 2 # 连接池中的最小空闲连接 默认 0
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1

server:
  port: 8088